In [1]:
4+4

8

In [2]:
from keyword import kwlist

In [3]:
kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [4]:
len(kwlist)

36

In [5]:
a=3
b=4
c=6


In [6]:
print(a,b,c ,sep="\t")

3	4	6


In [7]:
a&b



0

In [8]:
a|b

7

In [9]:
a^b

7

In [11]:
print(4,5,6, end='\t')
print(7,8,9)

4 5 6	7 8 9


In [52]:
s= ('hello, this is a new process')

In [44]:
print(s)

hello, this is a new process


In [18]:
len(s)

28

In [19]:
type(s)

str

In [20]:
s[0]

'h'

In [21]:
#slicing- [begin:end:step size]

s[0:5:1]

'hello'

In [22]:
s[-7:28:1]

'process'

In [23]:
s[-1:-8:-1]

'ssecorp'

In [33]:
s[4:-29:-1]

'olleh'

In [31]:
s[7:14:1]

'this is'

In [32]:
print(s)

hello, this is a new process


In [34]:
s[-10:]

'ew process'

In [36]:
s[:-8:-1]

'ssecorp'

In [37]:
"hi" *10

'hihihihihihihihihihi'

In [38]:
'hi'+'bye'

'hibye'

In [53]:
s+=' here'

In [54]:
s

'hello, this is a new process here'

In [55]:
s = s[:5] +' Ankit'+ s[5:]
s

'hello Ankit, this is a new process here'

In [56]:
s[0]='g'

TypeError: 'str' object does not support item assignment

In [57]:
del s[0]

TypeError: 'str' object doesn't support item deletion

In [58]:
len(s)

39

In [59]:
s

'hello Ankit, this is a new process here'

In [64]:
a=[23,'39',[4,2,5]]
print(a)

[23, '39', [4, 2, 5]]


In [67]:
a[-1][1]

2

In [68]:
a+=[10,20]

In [69]:
a

[23, '39', [4, 2, 5], 10, 20]

In [72]:
a+=['Hello']
a

[23, '39', [4, 2, 5], 10, 20, 'Hello', 'Hello']

In [75]:
del a[-2]

In [82]:
a

[23, '39', 10, 20, 'Hello']

In [86]:
a[0]= 3
a

[3, '39', 10, 20, 'Hello']

In [87]:
g=(5,6,7,8,9)
g

(5, 6, 7, 8, 9)

In [90]:
len(g)

5

In [93]:
a += {'a1':3 , 'b1':39}
a

[3, '39', 10, 20, 'Hello', 'a1', 'b1']

In [96]:
d= {'a1':3 , 'b1':39}
print(d)
print(len(d))
print(type(d))
print(d['a1'])

{'a1': 3, 'b1': 39}
2
<class 'dict'>
3


In [97]:
d['c1'] =[9,2,3,6]

In [98]:
d

{'a1': 3, 'b1': 39, 'c1': [9, 2, 3, 6]}

In [99]:
del d['b1']

In [100]:
d

{'a1': 3, 'c1': [9, 2, 3, 6]}

In [101]:
h={4,5,6,7,8,9,3,2,1,7,8,7,9,0,0}
h

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [1]:
a = 10
b = 10.0
c = 10 + 0j
d = 'hello'
e = [3,6,2]
f = (3,6,2)
g = {'a': [45,6], 'b':[1,6,2]}
h = {5,2,8}
i = True

In [2]:
type(a)

int

In [3]:
a.real   # as a is an object of a integer class so here real is not a function in class we have some functions and some variables so real is a variable here

10

In [4]:
# STRING FUNCTIONS RETURN SOMETHING
print(d.count('l'))     # USE TO COUNT NUMBER OF OCCURENCES
print(d.index('e'))
print(d.find('l'))
print(d.split('l'))
print(d.strip('o'))     # by default it removes trailing and heading spaces or if we provide any value it will remove it from front and last
print(d.replace('l','L'))
print(d,end='\n\n')
print(d.join('wow'))
print(d.upper())
print(d.lower())
print(d.islower())
print(d.isupper())
print(d.isalpha())


# STRING ALL FUNCTIONS RETURN SOMETHING

2
1
2
['he', '', 'o']
hell
heLLo
hello

whelloohellow
HELLO
hello
True
False
True


In [5]:
'     this is strip     '.strip()

'this is strip'

In [7]:
'     this is strip     '.split('i')

['     th', 's ', 's str', 'p     ']

In [8]:
'awesome'.join('bakwas')

'bawesomeaawesomekawesomewawesomeaawesomes'

In [9]:
'-'.join('bakwas')

'b-a-k-w-a-s'

In [10]:
' wow '.join(['hi', 'there', 'to', 'nice'])

'hi wow there wow to wow nice'

In [11]:

# old way
days = 10
"This will last at most %d days"%(days)

'This will last at most 10 days'

In [12]:
days = 10
s = f"This will last at most {days} days"
s

'This will last at most 10 days'

In [15]:
# String types
#- Ordinary strings
#- F-string
#- Raw-string       r'this is \n raw string'            used for files location
#- byte-string      b 'this is a byte string'
r'this is raw \n string'

'this is raw \\n string'

In [16]:
# use format function when string declaration is present first and variable declaration is done after that in that case format() is our saviour
s = "this will last at most {} days and extra {}"
days = 10
extra = 5
s = s.format(days, extra)
print(s)

this will last at most 10 days and extra 5


In [17]:
s = "this will last at most {1} days and extra {0}"
days = 10
extra = 5
s = s.format(days, extra)
print(s)

this will last at most 5 days and extra 10


In [18]:
s = "this will last at most {1} days in {1} and extra {0}"
days = 10
extra = 5
s = s.format(days, extra)
print(s)

this will last at most 5 days in 5 and extra 10


In [20]:
e

[2, 2, 3, 4, 6, 50, 100]

In [19]:
#LIST FUNCTIONS      ---> some functions will return some will update some will do both
e.append(50); print(e)
print(e.count(10))
e.extend([4,6,2,3]); print(e)              # IN VALUES KO ALAG ALAG INSERT KREGA
print(e.index(4))
e.insert(2, 100); print(e)
print(e.pop()); print(e)
e.remove(6); print(e)
e.reverse(); print(e)
e.sort(); print(e)

#e.clear()
e1 = e.copy()       # SHALLOW COPY it will do no impact
e2 = e              # DEEP COPY



[3, 6, 2, 50]
0
[3, 6, 2, 50, 4, 6, 2, 3]
4
[3, 6, 100, 2, 50, 4, 6, 2, 3]
3
[3, 6, 100, 2, 50, 4, 6, 2]
[3, 100, 2, 50, 4, 6, 2]
[2, 6, 4, 50, 2, 100, 3]
[2, 2, 3, 4, 6, 50, 100]


In [21]:
# shallow copy vs Deep copy
e1,e2

([2, 2, 3, 4, 6, 50, 100], [2, 2, 3, 4, 6, 50, 100])

In [22]:
e2 is e

True

In [23]:
e2.append(1000)

In [24]:
e,e2

([2, 2, 3, 4, 6, 50, 100, 1000], [2, 2, 3, 4, 6, 50, 100, 1000])

In [25]:
e1.append(2000)

In [26]:
e,e1

([2, 2, 3, 4, 6, 50, 100, 1000], [2, 2, 3, 4, 6, 50, 100, 2000])

In [27]:
# TUPLE FUNCTIONS
print(f)
print(f.index(3))
print(f.count(3))

(3, 6, 2)
0
1


In [28]:
# DICTIONARY FUNCTIONS
print(g)
print(g.keys())
print(g.values())
print(g.get('a'))
print(g.pop('b')); print(g)

{'a': [45, 6], 'b': [1, 6, 2]}
dict_keys(['a', 'b'])
dict_values([[45, 6], [1, 6, 2]])
[45, 6]
[1, 6, 2]
{'a': [45, 6]}


In [29]:
g.update({'c':34})
print(g)

{'a': [45, 6], 'c': 34}


In [30]:
# SET FUNCTION
print(h)                   # we can perform some operations with the help of functions
h.add(50); print(h)
print(h.difference({2,10}))
print(h.intersection({2,10}))
h.pop(); print(h)       # FIFO
h.remove(50); print(h)
print(h.union({10,20,30,40}))

{8, 2, 5}
{8, 2, 50, 5}
{8, 50, 5}
{2}
{2, 50, 5}
{2, 5}
{2, 20, 5, 40, 10, 30}


In [31]:
str(a)

'10'

In [32]:
int('3000')

3000

In [33]:
#int('30.4')
int(float('30.4'))

30

In [34]:
eval('45') # it evaluate string to python code

45

In [35]:
d

'hello'

In [36]:
list(d)

['h', 'e', 'l', 'l', 'o']

In [37]:
tuple(d)

('h', 'e', 'l', 'l', 'o')

In [38]:
str(['a', 'g', 2,3])

"['a', 'g', 2, 3]"

In [39]:
dict(b=e)

{'b': [2, 2, 3, 4, 6, 50, 100, 1000]}

In [40]:
set(e)

{2, 3, 4, 6, 50, 100, 1000}

In [41]:
list(set(e))

[2, 3, 4, 100, 6, 1000, 50]

In [42]:
e1,e2

([2, 2, 3, 4, 6, 50, 100, 2000], [2, 2, 3, 4, 6, 50, 100, 1000])

In [43]:
[e1,e2]

[[2, 2, 3, 4, 6, 50, 100, 2000], [2, 2, 3, 4, 6, 50, 100, 1000]]

In [44]:
[*e1, *e2]       # iske andar jo items h unko mein entities manunga or then iterate krunga

# *e1 apne aap ko as a tuple smj k kam krta hai

[2, 2, 3, 4, 6, 50, 100, 2000, 2, 2, 3, 4, 6, 50, 100, 1000]

In [45]:
g1 = {'a':4, 'b': [5,6]}
g2 = {'c': 34, 'a': 'h1'}

In [46]:
g1 += g2

TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'

In [47]:
g1.update(g2)         # there is a nuksan value of g is updated but not concatena
g1

{'a': 'h1', 'b': [5, 6], 'c': 34}

In [48]:
{**g1, **g2}              # here none of the dictionary is get updated ** behaves as a tuple

{'a': 'h1', 'b': [5, 6], 'c': 34}

In [49]:
g3 = {1:11, 2:22}
{**g1, **g2, **g3} 

{'a': 'h1', 'b': [5, 6], 'c': 34, 1: 11, 2: 22}

In [50]:
# CONTROL STATEMENTS
####################
if-elif-else  (pass)       # conditional statement

while-else    (continue, break)       # Looping statement
for-else             

try-except-else-finally     # handling statement


#   Suites it is a concept of indentation with colon
statement:
    expr1
    expr2
statement2:
    expr3
    expr4
    statement3:
        expr5
    expr6
expr7

SyntaxError: invalid syntax (2819714667.py, line 3)

In [51]:
a = 30; b = 40; c=29;
if a>=b and a>=c:
    print(a)
elif b>=c and b>=a:
    print(b)
else:
    print(c)

40


In [52]:
a = 30
while(a>0):
    print('hello')
    a -= 7
    if a==16:
       continue
       #break
    print('achha')
else:
    print('oh')

hello
achha
hello
hello
achha
hello
achha
hello
achha
oh


In [53]:
# for (int i=0;i<n;i++)
# {
#     do so
# }
arr = [3,4,5,6]
# foreach(var v in arr){
#     v

for i in arr:
    print(i, i*10) 


# FOR LOOP IS FOR SOMETHING WHEN WE NOW NUMBER OF ITERATIONS, WHILE LOOP IS FOR WHERE WE KNOW CONDITION

3 30
4 40
5 50
6 60


In [54]:
table = [1,2,3,4,5,6,7,8,9,10]
num = 2
for i in table:
    print(i * num)

2
4
6
8
10
12
14
16
18
20


In [55]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [56]:
for i in range(1,11,1):
    print(num*i)

2
4
6
8
10
12
14
16
18
20


In [57]:
for i in range(1,6):
    print(i * '* ')

* 
* * 
* * * 
* * * * 
* * * * * 


In [58]:
# Comprehensions             used at places where i need some values to pass as an argument without storing them into memory,     it is not easily readable
# -------------------
# conditional (not really a comprehension though)
# list
# dict
# set
# Generator


# USE WHEN I NEED TO CREATE LIST BY MAKING USE OF LOOPS


In [59]:
a = [3,4,5,6,4,3,5,6,7,3,3,2,5]

In [60]:
b = []
for i in a:
    #b.append(i*2)
    b += [i*2]
print(b)

[6, 8, 10, 12, 8, 6, 10, 12, 14, 6, 6, 4, 10]


In [61]:
# [ output  for-loop  if-condition] 
#[ output  for-loop ]
b1 = [i*2 for i in a ]
b1

[6, 8, 10, 12, 8, 6, 10, 12, 14, 6, 6, 4, 10]

In [62]:
b2 = [i for i in a if i%2==1]
b2

[3, 5, 3, 5, 7, 3, 3, 5]

In [63]:
b2 = [
        i
        for i in a
        if i%2 == 1
]
b2

[3, 5, 3, 5, 7, 3, 3, 5]

In [64]:
# CONDITIONAL COMPREHENSION
num = 33
print('odd') if num%2 else print('Even')

odd


In [65]:
b3 = [ f'{i} odd' if i%2 else f'{i} even' for i in a]
b3

['3 odd',
 '4 even',
 '5 odd',
 '6 even',
 '4 even',
 '3 odd',
 '5 odd',
 '6 even',
 '7 odd',
 '3 odd',
 '3 odd',
 '2 even',
 '5 odd']

In [66]:
{i : i**2 for i in a}

{3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 2: 4}

In [67]:
{i**2 for i in a}

{4, 9, 16, 25, 36, 49}

In [68]:
(i )

5

In [69]:
#day4

In [71]:
# user defined functions

In [72]:
def kuchbhi():
    print('hi')

kuchbhi()

hi


In [73]:
# types of functions
# 1. No input, No output
# 2. Input, but no output
# 3. No input, but output
# 4. with input, with output


In [74]:
def abc1():
    print('Its no input no output function')

def abc2(x):
    print(f'its fetching x = {x} but no output')

def abc3():
    return "Its a string returned from function as output"

def abc4(x,y):
    return x*2, y+x+y               # A function cannot return more then 1 values it will return a tuple if values are more then one

In [75]:
a = abc1()
print(a)

Its no input no output function
None


In [76]:
a = abc3()
print(a)

Its a string returned from function as output


In [77]:
a4 = abc4(5,8)
print(a4)

(10, 21)


In [78]:
a41, a42 = abc4(5,8)
print(a41, a42 , sep='\n')

10
21


In [79]:
abc4(y=5, x=8)

(16, 18)

In [80]:
abc4(5, y=10)

(10, 25)

In [81]:
abc4(y=5, 8)   # positional argument must be written after keyword argument
# not allowed

SyntaxError: positional argument follows keyword argument (1129109727.py, line 1)

In [82]:
abc4(5)

TypeError: abc4() missing 1 required positional argument: 'y'

In [83]:
abc4(5,8,9)

TypeError: abc4() takes 2 positional arguments but 3 were given

In [96]:
abc4(x=9, y=4, z=10)

TypeError: abc4() got an unexpected keyword argument 'z'

In [97]:
# Default values to function argument
def abc5(x,y=0):                            # Default values must be from right hand side
    return x*2, y+x+y

In [98]:
abc5(4)

(8, 4)

In [99]:
abc5(4,7)

(8, 18)

In [100]:
def abc5(x=1,y=0):                            # Default values must be from right hand side
    return x*2, y+x+y

print(abc5())
print(abc5(4))
print(abc5(4,5))

(2, 1)
(8, 4)
(8, 14)


In [101]:
# *args, **kwargs they should also present at last
def abc6(x=1,y=0,*p, **q):
    print(x*2, y+x+y)
    print(p)
    print(q)
    print('')

In [102]:
abc6()
abc6(5,4)
abc6(5,4,3,4,56,7,'hii','by')
abc6(5,4,3,4,56,7,'hii','by', m=23,n=[4,7,8])

abc6(5,4,3,4,56,7,'hii','by', p=23,q=[4,7,8])

abc6(5,4,3,4,56,7,'hii','by', 23, **{'f':[45,6], 'z':34})

2 1
()
{}

10 13
()
{}

10 13
(3, 4, 56, 7, 'hii', 'by')
{}

10 13
(3, 4, 56, 7, 'hii', 'by')
{'m': 23, 'n': [4, 7, 8]}

10 13
(3, 4, 56, 7, 'hii', 'by')
{'p': 23, 'q': [4, 7, 8]}

10 13
(3, 4, 56, 7, 'hii', 'by', 23)
{'f': [45, 6], 'z': 34}



In [103]:
# ERROR AND EXCEPTION HANDLING
    # try-except-else-finally
    # Built-in functions

In [105]:
try:
    a = 10
    b = int(input('Enter the number : '))
    print(a/b)
except ValueError as err:
    print(err,b)
    print(a)
except ZeroDivisionError as err:
    print(err,b)
    print(a)
except KeyboardInterrupt as err:
    print(err)
    print('oh aap kam nii krna chate')
except Exception as err:
    print(err)

print('kam ho gya')

invalid literal for int() with base 10: '' [8, 14, 16, 8, 16]
10
kam ho gya


In [106]:
try:
    a = 10
    b = int(input('Enter the number : '))
    print(a/b)
# except ValueError as err:
#     print(err,b)
#     print(a)
# except ZeroDivisionError as err:
#     print(err,b)
#     print(a)
# except KeyboardInterrupt as err:
#     print(err)
#     print('oh aap kam nii krna chate')
except Exception as err:
    print(err)

print('kam ho gya')

invalid literal for int() with base 10: ''
kam ho gya


In [107]:
try:
    a = 10
    b = int(input('Enter the number : '))
    print(a/b)
except ValueError as err:
    print(err,b)
    print(a)
# except ZeroDivisionError as err:
#     print(err,b)
#     print(a)
# except KeyboardInterrupt as err:
#     print(err)
#     print('oh aap kam nii krna chate')
# except Exception as err:
#     print(err)
else:
    print('sab bhadiya')
finally:
    print('Marte marte raaz btake jauunga')

print('kam ho gya')

invalid literal for int() with base 10: '' [8, 14, 16, 8, 16]
10
Marte marte raaz btake jauunga
kam ho gya


In [108]:
# Scope of variable


## In Python a function can be 
#### assigned to a variable
#### can be passed as an argument to a function
#### can be defined inside another function
#### returned from another function 

In [109]:
a = 10
def xyz():
    print(a)
print(a)
xyz()

10
10


In [110]:
a = 10
def xyz():
    global a
    a += 20    
    print(a)
print(a)
xyz()
print(a)

10
30
30


In [111]:
def abc(x,y):
    return x+y

In [112]:
#k = abc(3,4)
k = abc

In [113]:
abc

<function __main__.abc(x, y)>

In [114]:
k

<function __main__.abc(x, y)>

In [115]:
def pot():
    print("pot")

In [116]:
def pqr(f):
    f()

In [117]:
pqr(pot)

pot


In [118]:
def basket():
    def dox():
        print('nox')
    dox()

basket()

nox


In [119]:
def awesome(f, m, n):
    return f, m+n

In [120]:
p = awesome(pot, 3,4)

In [121]:
p[0]()

pot


In [122]:
# OOOORRRRRR
p, _ = awesome(pot,3,4)

In [123]:
p()

pot


In [125]:
_

7

In [126]:
####  DECORATOR  ----> it is a concept in python which might help for inheritance
def decorate(f):
    def special():
        print('ye to special hai')
        f()
        print('Decorate ho gya')
    return special

In [127]:
def simple():
    print('mein to bhoot simple hu')

simple=decorate(simple)

In [128]:
simple()

ye to special hai
mein to bhoot simple hu
Decorate ho gya


In [129]:
####  DECORATOR  ----> it is a concept in python which might help for inheritance
def nayaWala(f):
    def special():
        print('ye to special hai')
        f()
        print('Decorate ho gya')
    return special

In [130]:
@nayaWala
@nayaWala
def simple():
    print('mein to bhoot simple hu')

simple=decorate(simple)

In [131]:
simple()

ye to special hai
ye to special hai
ye to special hai
mein to bhoot simple hu
Decorate ho gya
Decorate ho gya
Decorate ho gya


In [132]:
def akii():
    print('akshay')

In [133]:
def dec1(f):
    def fun():
        print('this is inside dec fun')
        f()
        print('decorate is done')
    return fun

In [134]:
k = dec1(akii)

In [135]:
k()

this is inside dec fun
akshay
decorate is done


In [136]:
## Annonymous Functions
#######################
# Lambda Expression                              these are one liners


# lambda ip_args: op_args                      op_args behaviour is that they are always returned

In [137]:
def normal(x,y):
    return x*y

m = normal(3,4)
print(m)

12


In [138]:
normals = lambda x, y: x * y
normals(4,5)

20

In [139]:
def my_mapper(func, values):
    result = []
    for value in values:
        result += [func(value)]
    return result

data = [6,7,4,3,3,5]
print(my_mapper(lambda x:x*2, data))
print(my_mapper(lambda x:x*2 if x%2 else x/2, data))
print(my_mapper(lambda x:str(x), data))


# def first(v):
#     return v*2
# def second(v):
#     return v*2 if v%2 else v/2
# def third(v):
#     return str(v)

# print(my_mapper(first,data))
# print(my_mapper(second,data))
# print(my_mapper(third,data))

[12, 14, 8, 6, 6, 10]
[3.0, 14, 2.0, 6, 6, 10]
['6', '7', '4', '3', '3', '5']


In [84]:
#day5

In [86]:
a=[4,7,8,4,8]
def makeGen(data):
    for i in data:
        yield i
      
b=[]
for i in makeGen(a):
    b.append(i*2)
print(b)         

[8, 14, 16, 8, 16]


In [88]:
#map()
#filter()

In [89]:
a

[4, 7, 8, 4, 8]

In [ ]:
def my_map(func,data):
    for d in data:
        yield func(d)
def my_filter(func,data):
    for d in data:
     if func(d):
        yield d        

In [90]:
b1 = map(lambda x:x*2,a)
b2 = map(lambda x:x*2 if x%2 else x/2,a)
print(b1)
print(b2)

In [4]:
p = [34,7,3,7,4,62,4,6,7,7]
p1=[i for i in p if i%2]              #comprehension
p2=filter(lambda x:x%2==1,p)
print(p1)
print(p)
print(list(p2))

[7, 3, 7, 7, 7]
[34, 7, 3, 7, 4, 62, 4, 6, 7, 7]
[7, 3, 7, 7, 7]


In [5]:
x=[3,8,6,9]
y=[9,4,6,2]
print(x+y)
print(list(zip(x,y)))                   #zip concatinates the two lists vertically

[3, 8, 6, 9, 9, 4, 6, 2]
[(3, 9), (8, 4), (6, 6), (9, 2)]


In [ ]:
#Library/Framework/Module/Package

#.py - Module
#python -m pip install numpy
#python -m pip install whatibroughtinstallthat .whl


NUMPY DAY 7

In [3]:
!python -m pip install numpy

You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np

In [6]:
a=np.array([3,4,5,6,4])
a

array([3, 4, 5, 6, 4])

In [7]:
def show_arr(arr):
 print(a.shape)
 print(a.size)
 print(a.dtype)
 len(a)
 print(a.ndim)

In [8]:
b= np.array([[[10,100],[11,110],[13,130],[14,140]],#fetch(2*2*2)
             [[45,145],[22,122],[9,19],[2,12]],#fetch(1*2*2),fetch(2*1*1)
             [[6,16],[5,15],[1,11],[8,18]]])#comma seperted is rows , fetch(3*1*1)
b
show_arr(a)
b.ndim

(5,)
5
int32
1


3

In [9]:
#array operation
# item accessing-subscripting, slicing
# item assignment
# item insertino
# item deletion
# arithmetic

In [10]:
c=np.array([[10,11,13,14],[45,22,9,2],[6,5,1,8]])#fetch (1*4)
#subrscripting-accessing from 3d [1st:1st end: stepsize, 2nd,3rd]
c[0,0]
c[1, -3:]
c[:, -2]
c[:, -2:-1]

array([[13],
       [ 9],
       [ 1]])

In [11]:
c[:, -2].shape

(3,)

In [12]:
#ans-
#1*4
print(c[-1:,:1])
#1*2*2-
print(b[:1,:2,:1])
#3*1*1
print(b[:,1:2,:1])
#2*1*1
print(b[-2:, -1:,:1])
#2*2*2
print(b[:2,-2:, :])

[[6]]
[[[10]
  [11]]]
[[[11]]

 [[22]]

 [[ 5]]]
[[[2]]

 [[8]]]
[[[ 13 130]
  [ 14 140]]

 [[  9  19]
  [  2  12]]]


In [13]:
#item assignment
c[1,2]=90
c

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [14]:
#item insertion
#1d
a=np.append(a,80)
a
#2d
np.append(c,[[9,90,900,9000]],axis=0)#axis 0 = row, 1->column

array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   9,   90,  900, 9000]])

In [15]:
np.append(c,[[9],[90],[900]],axis=1)

array([[ 10,  11,  13,  14,   9],
       [ 45,  22,  90,   2,  90],
       [  6,   5,   1,   8, 900]])

In [16]:
#deletion, #single element cannot be deleted
c
c1=c.copy()

In [17]:
np.delete(c1, 0, axis=0)

array([[45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [18]:
#arithmetic operations
c1-20

array([[-10,  -9,  -7,  -6],
       [ 25,   2,  70, -18],
       [-14, -15, -19, -12]])

In [19]:
c1+20

array([[ 30,  31,  33,  34],
       [ 65,  42, 110,  22],
       [ 26,  25,  21,  28]])

In [20]:
c1*2

array([[ 20,  22,  26,  28],
       [ 90,  44, 180,   4],
       [ 12,  10,   2,  16]])

In [21]:
#array manupiplation
#arr reshape
c1.reshape(2,6,1)

array([[[10],
        [11],
        [13],
        [14],
        [45],
        [22]],

       [[90],
        [ 2],
        [ 6],
        [ 5],
        [ 1],
        [ 8]]])

In [22]:
#arr.astype()
c1.astype(float)

array([[10., 11., 13., 14.],
       [45., 22., 90.,  2.],
       [ 6.,  5.,  1.,  8.]])

In [23]:
c1.astype('uint16')

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]], dtype=uint16)

In [24]:
#more functions to create array
#np.array()
#np.arange()->array version of range func, also allows float
#np.linspace()->start,end,no. of items
#np.ones()->generate all values as '1'
#np.zeroes()->generate all values
#np.random.random()
#mp.random.randint()

In [25]:
np.ones((3,4),dtype='int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

day 8 numpy


In [27]:
!python -m pip install matplotlib
!python -m pip install opencv-python
!python -m pip install scikit-image
!python -m pip install pillow

You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [28]:
!python -m pip install tensorflow


  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\~umpy\\.libs\\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll'
Consider using the `--user` option or check the permissions.

You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [29]:
import numpy as np

In [31]:
import cv2
import skimage
import matplotlib.pyplot as plt


In [33]:
cv2.__version__

'4.8.0'